In [43]:
import pandas as pd
import copy
from astropy import units as u

In [95]:
class UnitDataFrame(pd.DataFrame):
    def __init__(self, *args, units={}, **kwargs):
        super().__init__(*args, **kwargs)
        for colname, unit in units.items():
            self.applyUnit(colname, unit)
        
    def __repr__(self):
        return repr(self.to_unitless())
    
    def _repr_html_(self):
        return self.to_unitless()._repr_html_()
        
    def applyUnit(self, colname, unit):
        self[colname] = self[colname].values * unit
        
    def to_unitless(self):
        new_df = pd.DataFrame()
        for col in self.columns:
            unit = self[col].values.unit
            new_df[col] = self[col].values.to_value(unit)
            new_df = new_df.rename(columns = {col : f'{col} [{str(unit)}]'})
        return new_df
            
            
        
np.random.seed(1)
udf = UnitDataFrame({
        'x' : np.random.rand(8),
        't' : np.random.rand(8),
        },
        units = {
            'x' : u.m,
            't' : u.s,
        }
    )

udf['v'] = udf.x/udf.t
udf['a'] = udf.v/udf.t
udf

      x [m]     t [s]  v [m / s]  a [m / s2]
0  0.417022  0.396767   1.051049    2.649030
1  0.720324  0.538817   1.336864    2.481110
2  0.000114  0.419195   0.000273    0.000651
3  0.302333  0.685220   0.441220    0.643911
4  0.146756  0.204452   0.717800    3.510846
5  0.092339  0.878117   0.105155    0.119751
6  0.186260  0.027388   6.800897  248.320375
7  0.345561  0.670468   0.515403    0.768721